# BACKGROUND
background {
    monitor =
    path = ~/.local/share/wallpapers/a7x-purple.png
    blur_passes = 2
    blur_size = 6
}

# CLOCK
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(b2aad3ff)
    font_size = 80
    font_family = Sarasa Term CL
    position = 0, 200
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"
    color = rgba(b2aad3cc)
    font_size = 22
    font_family = Sarasa Term CL
    position = 0, 130
    halign = center
    valign = center
}

# PASSWORD INPUT
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 1
    rounding = 0

    outer_color = rgba(332d49ff)
    inner_color = rgba(000000cc)
    font_color = rgba(b2aad3ff)
    font_family = Sarasa Term CL

    fade_on_empty = false
    placeholder_text = <span foreground="##b2aad3">Password...</span>

    position = 0, -50
    halign = center
    valign = center
}
